apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    owner: platform-team
    purpose: platform-services
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    owner: platform-team
    purpose: application-workloads
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-team-a
  labels:
    owner: dev-team-a
    purpose: team-workloads